<?php

/**
 * @file
 * Reset all user accounts!
 */

/**
 * Implements hook_permission().
 */
function mass_pwreset_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    'administer pwreset' =>  array(
      'title' => t('Administer password resets'),
      'description' => t('Administer mass password reset settings and reset passwords.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mass_pwreset_menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */
  $items['admin/people/mass-pwreset'] = array(
    'title' => 'Mass Password Reset',
    'access arguments' => array('Administer password resets'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'mass_pwreset.admin.inc',
  );

  return $items;
}

function _mass_pwreset_reset_passwords() {
  $users = entity_load('user');
  $emails = '';
  foreach($users as $user) {
    if (array_key_exists(3, $user->roles)) {
      if (strlen($emails) > 0) {
        $emails .= ' ' . $user->mail;
      } else {
        $emails = $user->mail;
      }
    }
  }

}
